ARG  PHPVERSION=8.0
FROM php:${PHPVERSION}-apache
LABEL maintainer docker@katagena.com
LABEL org.label-schema.vcs-url="https://github.com/nouchka/docker-symfony"

ARG PHPVERSION=8.0
ARG PHPCONF=/etc/php/${PHPVERSION}
ARG REDISCLIENTVERSION=5.3.2
ARG DOCKER_TAG=${PHPVERSION}
ARG PUID=1000
ARG PGID=1000
LABEL version="${DOCKER_TAG}"

ENV PUID ${PUID}
ENV PGID ${PGID}
ENV SHELL /bin/bash

ENV SYMFONY_ENV=prod \
	SYMFONY_DIRECTORY=/var/www/

ENV APACHE_RUN_USER=www-data \
	APACHE_RUN_GROUP=www-data \
	APACHE_LOG_DIR=/var/log/apache2 \
	APACHE_LOCK_DIR=/var/lock/apache2 \
	APACHE_RUN_DIR=/var/run/apache2 \
	APACHE_PID_FILE=/var/run/apache2/apache2.pid

COPY start.sh /start.sh
COPY check.sh /check.sh

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
	&& apt-get -y install \
		curl=* \
		zip=* \
		unzip=* \
		git=* \
		bash-completion=* \
		--no-install-recommends && \
	a2enmod rewrite && \
	a2enmod macro && \
	a2enmod proxy && \
	a2enmod ssl && \
	a2enmod http2 && \
	a2enmod proxy_http && \
	a2dissite 000-default && \
	usermod -u ${PUID} www-data && \
	groupmod -g ${PGID} www-data && \
	usermod -s /bin/bash www-data && \
	mkdir -p /var/www/.composer && \
	chown -R www-data: /var/www && \
	echo "date.timezone = UTC" >> "$PHP_INI_DIR/conf.d/timezone.ini" && \
	mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" && \
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
	php /usr/local/bin/composer self-update && \
	curl -sS https://get.symfony.com/cli/installer | bash && \
	mv /root/.symfony/bin/symfony /usr/local/bin/symfony && \
	chmod a+x /usr/local/bin/symfony && \
	curl -LsS https://phar.phpunit.de/phpunit.phar  -o /usr/local/bin/phpunit && \
	chmod a+x /usr/local/bin/phpunit && \
	composer global require bamarni/symfony-console-autocomplete && \
	/root/.composer/vendor/bin/symfony-autocomplete composer > /etc/bash_completion.d/composer && \
	su - www-data -c 'echo "source /usr/share/bash-completion/bash_completion" >> ~/.bashrc' && \
	curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$REDISCLIENTVERSION.tar.gz \
	&& tar xfz /tmp/redis.tar.gz \
	&& rm -r /tmp/redis.tar.gz \
	&& mkdir -p /usr/src/php/ext/ \
	&& mv phpredis-$REDISCLIENTVERSION /usr/src/php/ext/redis \
	&& docker-php-ext-install redis && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	chmod +x /start.sh && \
	chmod +x /check.sh && \
	chmod +x /tini

HEALTHCHECK CMD /check.sh

WORKDIR /var/www

EXPOSE 80

ENTRYPOINT ["/tini", "--"]
CMD ["/start.sh"]
