ARG  PHPVERSION=7.4
FROM php:${PHPVERSION}-apache
LABEL maintainer docker@katagena.com
LABEL org.label-schema.vcs-url="https://github.com/nouchka/docker-symfony"

ARG PHPCONF=/etc/php/${PHPVERSION}
ARG DOCKER_TAG=${PHPVERSION}
ARG PUID=1000
ARG PGID=1000
LABEL version="${DOCKER_TAG}"

ENV PUID ${PUID}
ENV PGID ${PGID}
ENV SHELL /bin/bash

ENV SYMFONY_ENV=prod \
	SYMFONY_DIRECTORY=/var/www/

ENV APACHE_RUN_USER=www-data \
	APACHE_RUN_GROUP=www-data \
	APACHE_LOG_DIR=/var/log/apache2 \
	APACHE_LOCK_DIR=/var/lock/apache2 \
	APACHE_RUN_DIR=/var/run/apache2 \
	APACHE_PID_FILE=/var/run/apache2/apache2.pid

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
	&& apt-get update \
	&& apt-get -y install \
		curl \
		zip \
		unzip \
		git \
		--no-install-recommends \
	&& apt-get -y install \
		libmagickwand-dev \
		--no-install-recommends \
	&& pecl install imagick \
	&& pecl install redis \
	&& pecl install xdebug \
	&& apt-get -y install \
		libpq-dev \
		--no-install-recommends \
	&& docker-php-ext-install \
		pdo \
		pdo_pgsql \
		pgsql \
		pdo_mysql \
		opcache \
		intl \
	&& docker-php-ext-enable imagick redis xdebug && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	a2enmod rewrite && \
	a2enmod macro && \
	a2enmod proxy && \
	a2enmod ssl && \
	a2enmod http2 && \
	a2enmod proxy_http && \
	a2dissite 000-default && \
	usermod -u ${PUID} www-data && \
	groupmod -g ${PGID} www-data && \
	usermod -s /bin/bash www-data && \
	mkdir -p /var/www/.composer && \
	chown -R www-data: /var/www && \
	echo "date.timezone = UTC" >> $PHP_INI_DIR/conf.d/timezone.ini && \
	mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

##RUN
##	sed -i 's/session.save_handler = files/session.save_handler = redis/g' ${PHP_INI_DIR}/php.ini-development &&\
##	sed -i 's/session.save_handler = files/session.save_handler = redis/g' ${PHP_INI_DIR}/php.ini-production &&\
##	echo 'session.save_path = tcp://redis:6379' >> $PHP_INI_DIR/conf.d/docker-php-ext-redis.ini
	
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
	php /usr/local/bin/composer self-update && \
	curl -sS https://get.symfony.com/cli/installer | bash && \
	mv /root/.symfony/bin/symfony /usr/local/bin/symfony && \
	chmod a+x /usr/local/bin/symfony && \
	curl http://get.sensiolabs.org/php-cs-fixer.phar -o /usr/local/bin/php-cs-fixer && \
	chmod a+x /usr/local/bin/php-cs-fixer && \
	curl -LsS https://phar.phpunit.de/phpunit.phar  -o /usr/local/bin/phpunit && \
	chmod a+x /usr/local/bin/phpunit && \
	composer global require bamarni/symfony-console-autocomplete && \
	/root/.composer/vendor/bin/symfony-autocomplete composer > /etc/bash_completion.d/composer && \
	su - www-data -c 'echo "source /usr/share/bash-completion/bash_completion" >> ~/.bashrc'

COPY start.sh /start.sh
RUN chmod +x /start.sh

COPY check.sh /check.sh
RUN chmod +x /check.sh
HEALTHCHECK CMD /check.sh

WORKDIR /var/www

EXPOSE 80
ENTRYPOINT [ "/start.sh" ]
