version: '2'

services:
  symfony:
    build: .
    container_name: "symfony"
    ports:
      - "8080:80"
    environment:
      - SYMFONY_ENV=prod
      - SYMFONY_DIRECTORY=/var/www
      - SYMFONY_INIT_site1=True
      - SYMFONY_PREV_site1=./init.sh
      - SYMFONY_POST_site2=./launch.sh
    volumes:
      - ./samples/site1/001-vhost:/etc/apache2/sites-enabled/001-vhost
      - ./samples/site1:/var/www/site1
      - ./samples/site2:/var/www/site2
      - composer:/var/www/.composer

volumes:
  composer:
    driver: local
