version: '2'
services:
  symfony:
    image: nouchka/symfony
    container_name: "symfony"
    entrypoint: /start.sh
    ports:
      - "80:80"
    environment:
      SYMFONY_ENV: dev
      SYMFONY_DIRECTORY: /var/www
      SYMFONY_NAME: new_project
      APACHE_VHOST: 001-vhost
    volumes:
      - ./sites-available:/etc/apache2/sites-available
