#!/usr/bin/env bash

LATEST_VERSION="5"

if [ "$DOCKER_TAG" = "latest" ]; then
	PHPVERSION=$LATEST_VERSION
else
	PHPVERSION=$DOCKER_TAG
fi

if [ "$PHPVERSION" = "7.0" ]; then
	BASE_IMAGE=stretch
	PHPCONF=/etc/php/${PHPVERSION}
elif [ "$PHPVERSION" = "5" ]; then
	BASE_IMAGE=jessie
	PHPCONF=/etc/php${PHPVERSION}
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=PHPVERSION=$PHPVERSION \
	--build-arg=PHPCONF=$PHPCONF \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
