#!/usr/bin/env bash

LATEST_VERSION="7.4"

if [ "$DOCKER_TAG" = "beta" ]; then
	PHPVERSION=8.0
elif [ "$DOCKER_TAG" = "latest" ]; then
	PHPVERSION=$LATEST_VERSION
else
	PHPVERSION=$DOCKER_TAG
fi

PHPCONF=/etc/php/${PHPVERSION}

DOCKERFILE=Dockerfile
if [ "$DOCKER_TAG" = "beta" ]; then
	DOCKERFILE=Dockerfile-8
elif [ "$PHPVERSION" = "7.4" ]; then
	BASE_IMAGE=bullseye
elif [ "$PHPVERSION" = "7.3" ]; then
	BASE_IMAGE=buster
elif [ "$PHPVERSION" = "7.0" ]; then
	BASE_IMAGE=stretch
elif [ "$PHPVERSION" = "5" ]; then
	BASE_IMAGE=jessie
	PHPCONF=/etc/php${PHPVERSION}
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	-f $DOCKERFILE \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=PHPVERSION=$PHPVERSION \
	--build-arg=PHPCONF=$PHPCONF \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
